### ISSUE TITLE
Maybe Find Alternative to Nested Function Call for Model

### ISSUE THREAD

**Issue by nikosbosse** [epiforecasts/EpiSoon#31]
models are currently specified as functions in functions. 
Maybe there is a better / more easily understandable alternative to that

**Comment by nikosbosse** [comment]
Maybe pass a) a function and b) a list of parameters to that function?

**Comment by seabbs** [comment]
Happy to see this implemented so we can compare.

**Comment by seabbs** [comment]
Did you get anywhere with this. If no please close.
