### ISSUE TITLE
horizon > 7

### ISSUE THREAD

**Issue by philipus** [epiforecasts/EpiSoon#44]
I was experimenting with higher horizon number like 30

In this cases I think the Rt factor when going close to 0 for the forecast is overestimating the decline

Maybe one can fine a more conservative forecasting method or do you think it can be that for any european country Rt goes much below 1?

**Comment by seabbs** [comment]
Thanks for looking into this @philipus 

We don't actually use the `bsts` models for forecasting as they don't perform well at all. Other methods are less likely to push R down as far. 

The answer from an Epi point of view I think is that we don't know. We have explored various transforms (log, box cox etc) in model evaluation but none of them outperform no transform at the moment. However, I imagine this may change going forward
