### ISSUE TITLE
Visualising model scoring

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiSoon#54]
The output of `compare_timeseries` is complex and hard to use. Sensible visualizations can make understanding the scores easier. 

I have started (note this is a public-facing version of some work based on confidential data so may be slightly out of step) to think about how this can be visualised here: https://github.com/nikosbosse/covidevaluation/blob/master/R/evaluate_models.R

Wrapping some of these plots into package functions would be a great start to making our approach more easily adoptable by others.

**Comment by sbfnk** [comment]
Fixed in #77

**Comment by seabbs** [comment]
we probably want to depreciate this and instead depend more on `scoringutils`?
