### ISSUE TITLE
GitHub actions and travis

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/EpiSoon#55]
We currently are using both - it would be great to standardise around one. I have not personally used GitHub's actions but hear it may be the new kid on the block. 

Ideally, we would also automate documentation generation (i.e the pkgdown site) on new pull requests.

**Comment by medewitt** [comment]
@seabbs happy to sort out the GitHub actions if you want to go this way w/ the package check and website build.

**Comment by seabbs** [comment]
Thanks @medewitt that would be awesome!

**Comment by medewitt** [comment]
@seabbs whenever you have a moment, can you create a branch on this repo by doing the following:
```
git checkout --orphan gh-pages
git rm -rf .
git commit --allow-empty -m 'Initial gh-pages commit'
git push origin gh-pages
```
I have the GitHub actions set to build the pgkdown site in another branch, it just needs a home on the master repo and I'll need that orphan branch to build to

**Comment by seabbs** [comment]
Done! Nice one.

**Comment by seabbs** [comment]
Done by @medewitt
